apiVersion: v1
kind: Secret
metadata:
  name: isso-config
stringData:
  isso.cfg: |
    [general]
    dbpath = /db/comments.db
    host =
        http://www.tutorialworks.com/
        https://www.tutorialworks.com/
        http://localhost:4001/
    notify = smtp
    [server]
    listen = http://0.0.0.0:8080/
    [moderation]
    enabled = true
    purge-after = 365d
    [guard]
    enabled = true
    ratelimit = 2
    direct-reply = 3
    reply-to-self = true
    require-author = true
    require-email = false
    [smtp]
    username = ${SMTP_USERNAME}
    password = ${SMTP_PASSWORD}
    host = ${SMTP_SERVER}
    port = ${SMTP_PORT}
    security = ${SMTP_SECURITY}
    to = ${SMTP_EMAIL}
    from = ${SMTP_EMAIL}
    timeout = 10
    [admin]
    enabled = true
    password = ${ADMIN_PASSWORD}
