apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: plausible
    app.kubernetes.io/component: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plausible
      component: postgres
  template:
    metadata:
      labels:
        app: plausible
        component: postgres
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: postgres
        image: postgres:12
        name: postgres
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: postgres

