apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: plausible
    app.kubernetes.io/component: app
  name: plausible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plausible
  template:
    metadata:
      labels:
        app: plausible
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: plausible
        image: plausible/analytics:latest
        name: plausible
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

